export enum DomainEventType {
  RAW_PAYLOAD_RECEIVED = 'RAW_PAYLOAD_RECEIVED',
  PAYLOAD_NORMALIZED = 'PAYLOAD_NORMALIZED',
  EVIDENCE_CREATED = 'EVIDENCE_CREATED',
  GRAPH_MUTATION_CREATED = 'GRAPH_MUTATION_CREATED',
  GRAPH_PERSISTED = 'GRAPH_PERSISTED',
  PROJECTION_UPDATED = 'PROJECTION_UPDATED'
}