export enum EvidenceType {
  TRANSFER = 'TRANSFER',
  DEPLOYMENT = 'DEPLOYMENT',
  OWNERSHIP = 'OWNERSHIP',
  ASSOCIATION = 'ASSOCIATION',
  TOKEN_ACCOUNT = 'TOKEN_ACCOUNT',
  MINT_AUTHORITY = 'MINT_AUTHORITY',
  FREEZE_AUTHORITY = 'FREEZE_AUTHORITY',
  UPDATE_AUTHORITY = 'UPDATE_AUTHORITY',
  PROXY_LINKAGE = 'PROXY_LINKAGE',
  CONTRACT_CALL = 'CONTRACT_CALL',
  METADATA_UPDATE = 'METADATA_UPDATE'
}