export enum ProofLevel {
  ONCHAIN_PROOF = 'ONCHAIN_PROOF',
  CRYPTO_PROOF = 'CRYPTO_PROOF',
  STRUCTURAL = 'STRUCTURAL',
  BEHAVIORAL = 'BEHAVIORAL',
  HEURISTIC = 'HEURISTIC',
  UNKNOWN = 'UNKNOWN'
}