# -*- coding: utf-8 -*-
"""EAI Factory OS Local Runner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rwH_PwIPzVYKhvFQgCVtnG5I256R2VS
"""

import http.server
import socketserver
import webbrowser
import os
import threading
import time

# EAI Factory OS v4.0 HTML İçeriği
html_content = """
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EAI Factory OS | Edge-AI Command</title>
    <style>
        :root {
            --neon-cyan: #00f2ff;
            --neon-green: #39ff14;
            --ai-gold: #ffcc00;
            --alert-red: #ff3131;
            --bg-ultra-dark: #050608;
            --glass-bg: rgba(15, 20, 30, 0.7);
            --border-glow: rgba(0, 242, 255, 0.2);
            --edge-purple: #bd00ff;
        }

        * { box-sizing: border-box; }

        body {
            background-color: var(--bg-ultra-dark);
            background-image:
                linear-gradient(rgba(0, 242, 255, 0.03) 1px, transparent 1px),
                linear-gradient(90deg, rgba(0, 242, 255, 0.03) 1px, transparent 1px);
            background-size: 30px 30px;
            color: #e0e0e0;
            font-family: 'Inter', 'Segoe UI', Roboto, sans-serif;
            margin: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            overflow: hidden;
        }

        header {
            height: 75px;
            background: rgba(10, 10, 15, 0.95);
            backdrop-filter: blur(15px);
            border-bottom: 1px solid var(--border-glow);
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 0 30px;
            z-index: 100;
        }

        .system-branding h1 {
            margin: 0;
            font-size: 1.3rem;
            letter-spacing: 4px;
            color: white;
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .system-branding h1 span {
            color: var(--neon-cyan);
            font-weight: 900;
            text-shadow: 0 0 10px rgba(0, 242, 255, 0.5);
        }

        .status-container {
            display: flex;
            flex-direction: column;
            align-items: flex-end;
        }

        .pulse-online {
            display: flex;
            align-items: center;
            gap: 10px;
            font-size: 0.8rem;
            color: var(--neon-green);
            font-weight: bold;
            animation: status-pulse 2s infinite ease-in-out;
        }

        @keyframes status-pulse {
            0%, 100% { opacity: 1; text-shadow: 0 0 5px var(--neon-green); }
            50% { opacity: 0.7; text-shadow: 0 0 15px var(--neon-green); }
        }

        .dot {
            width: 8px;
            height: 8px;
            background: var(--neon-green);
            border-radius: 50%;
            box-shadow: 0 0 10px var(--neon-green);
            animation: blink 1.5s infinite;
        }

        .main-workspace {
            display: grid;
            grid-template-columns: 1fr 420px;
            gap: 15px;
            padding: 15px;
            flex: 1;
        }

        .visual-matrix {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            grid-template-rows: repeat(2, 1fr);
            gap: 12px;
        }

        .module {
            background: var(--glass-bg);
            border: 1px solid rgba(255, 255, 255, 0.05);
            position: relative;
            overflow: hidden;
            border-radius: 8px;
            box-shadow: inset 0 0 30px rgba(0,0,0,0.6);
        }

        .module::after {
            content: "";
            position: absolute;
            top: 0; left: 0; right: 0; height: 1.5px;
            background: linear-gradient(90deg, transparent, var(--neon-cyan), transparent);
            animation: scanline-h 6s infinite linear;
            z-index: 10;
        }

        .module img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            opacity: 0.5;
            transition: opacity 0.4s, transform 0.6s cubic-bezier(0.165, 0.84, 0.44, 1);
            filter: saturate(1.1) contrast(1.1);
        }

        .module:hover img { opacity: 0.8; transform: scale(1.05); }

        .label-tag {
            position: absolute;
            top: 15px;
            left: 15px;
            background: rgba(0, 0, 0, 0.85);
            border-left: 3px solid var(--edge-purple);
            padding: 5px 12px;
            font-size: 10px;
            font-weight: 800;
            z-index: 15;
            letter-spacing: 2px;
            text-transform: uppercase;
        }

        .eapu-viz {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            background: radial-gradient(circle at center, #1a1a2e 0%, #050608 100%);
        }

        .neural-load {
            font-size: 42px;
            font-weight: 900;
            color: var(--edge-purple);
            text-shadow: 0 0 20px rgba(189, 0, 255, 0.4);
        }

        .control-tower {
            display: flex;
            flex-direction: column;
            gap: 15px;
        }

        .ai-engine-stats {
            background: rgba(189, 0, 255, 0.04);
            border: 1px solid rgba(189, 0, 255, 0.2);
            padding: 18px;
            border-radius: 8px;
        }

        .ai-engine-stats h3 {
            margin: 0 0 12px 0;
            font-size: 13px;
            color: var(--edge-purple);
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .stat-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            margin-top: 10px;
        }

        .mini-stat {
            background: rgba(255,255,255,0.03);
            padding: 8px;
            border-radius: 4px;
            font-size: 11px;
        }

        .mini-stat label { display: block; color: #666; font-size: 9px; margin-bottom: 2px; }
        .mini-stat span { color: white; font-weight: bold; }

        .log-terminal {
            flex: 1;
            background: #000;
            border: 1px solid #222;
            padding: 15px;
            font-family: 'Consolas', monospace;
            font-size: 11px;
            color: #bd00ff;
            overflow-y: auto;
        }

        .log-row { margin-bottom: 8px; line-height: 1.5; border-bottom: 1px solid rgba(189, 0, 255, 0.05); padding-bottom: 4px; }
        .log-ts { color: #444; margin-right: 8px; }
        .log-success { color: var(--neon-green); }
        .log-info { color: var(--neon-cyan); }

        .btn-container {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
        }

        .action-button {
            background: transparent;
            border: 1px solid var(--edge-purple);
            color: var(--edge-purple);
            padding: 18px;
            font-weight: 900;
            letter-spacing: 2px;
            cursor: pointer;
            transition: 0.3s;
            text-transform: uppercase;
            font-size: 11px;
        }

        .action-button:hover {
            background: rgba(189, 0, 255, 0.1);
            box-shadow: 0 0 15px rgba(189, 0, 255, 0.2);
        }

        .action-button.primary {
            border-color: var(--neon-cyan);
            color: var(--neon-cyan);
        }

        footer {
            height: 45px;
            background: #010101;
            border-top: 1px solid #1a1a1a;
            display: flex;
            align-items: center;
            padding: 0 30px;
            gap: 20px;
            font-size: 10px;
            color: #555;
        }

        .badge {
            background: rgba(255,255,255,0.02);
            padding: 4px 10px;
            border-radius: 4px;
            border: 1px solid #222;
        }

        .badge b { color: #eee; margin-left: 5px; }

        @keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0.2; } }
        @keyframes scanline-h { 0% { top: -10%; } 100% { top: 110%; } }
    </style>
</head>
<body>

<header>
    <div class="system-branding">
        <h1><span>EAI</span> FACTORY OS v4.0</h1>
        <div style="font-size: 10px; color: #444; margin-top: 2px; letter-spacing: 1px;">DECENTRALIZED EDGE-AI INFRASTRUCTURE</div>
    </div>

    <div class="status-container">
        <div class="pulse-online">
            <div class="dot"></div>
            <span>EAI_NODE_7_ALPHA: ACTIVE</span>
        </div>
        <div id="realtime-clock" style="font-size: 11px; margin-top: 4px; color: #666; font-family: monospace;">00:00:00</div>
    </div>
</header>

<main class="main-workspace">
    <div class="visual-matrix">
        <div class="module">
            <div class="label-tag">EDGE_FEED_01: NPU ANALYSIS</div>
            <img src="https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=1000" alt="Robotics Production">
        </div>
        <div class="module">
            <div class="label-tag">EDGE_FEED_02: OBJECT SEGMENTATION</div>
            <img src="https://images.unsplash.com/photo-1563911191333-dc25039f607c?auto=format&fit=crop&w=1000" alt="Technical Parts">
        </div>
        <div class="module eapu-viz">
            <div class="label-tag">EAPU_04 CORE LOAD</div>
            <div class="neural-load" id="neural-load">42.8%</div>
            <div style="width: 60%; height: 2px; background: #111; margin-top: 10px; position: relative;">
                <div id="neural-bar" style="position: absolute; height: 100%; background: var(--edge-purple); width: 42%; transition: 0.5s;"></div>
            </div>
        </div>
        <div class="module">
            <div class="label-tag">EDGE_FEED_03: THERMAL_AI</div>
            <img src="https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&w=1000" style="filter: hue-rotate(240deg) saturate(2);">
        </div>
    </div>

    <div class="control-tower">
        <div class="ai-engine-stats">
            <h3>🤖 EAI CO-PILOT ADVISORY</h3>
            <div class="stat-grid">
                <div class="mini-stat"><label>NPU TEMP</label><span id="npu-temp">42.4°C</span></div>
                <div class="mini-stat"><label>TPU LOAD</label><span>18%</span></div>
                <div class="mini-stat"><label>INFERENCE TIME</label><span id="inf-time">1.2ms</span></div>
                <div class="mini-stat"><label>MODEL VERSION</label><span>v8.4.2-Nexus</span></div>
            </div>
        </div>

        <div class="log-terminal" id="terminal">
            <div class="log-row"><span class="log-ts">[00:01:15]</span> <span class="log-success">EAI:</span> Object recognition model v8.4 active.</div>
            <div class="log-row"><span class="log-ts">[00:01:30]</span> <span class="log-success">BOOT:</span> Edge processing unit EAPU_04 operational.</div>
        </div>

        <div class="btn-container">
            <button class="action-button primary" onclick="runDiag()">RUN DIAGNOSTICS</button>
            <button class="action-button" onclick="scale()">SCALE CLUSTER</button>
        </div>
    </div>
</main>

<footer>
    <div class="badge">EAI_LATENCY: <b id="latency">1.2ms</b></div>
    <div class="badge">NPU_LOAD: <b id="npu-load">24%</b></div>
    <div class="badge">NETWORK: <b>6G_LOCAL_MESH</b></div>
</footer>

<script>
    function updateClock() {
        document.getElementById('realtime-clock').innerText = new Date().toLocaleTimeString('tr-TR');
    }
    setInterval(updateClock, 1000);
    updateClock();

    setInterval(() => {
        const load = (35 + Math.random() * 20).toFixed(1);
        document.getElementById('neural-load').innerText = load + "%";
        document.getElementById('neural-bar').style.width = load + "%";
        document.getElementById('npu-temp').innerText = (40 + Math.random() * 5).toFixed(1) + "°C";
        document.getElementById('inf-time').innerText = (1.1 + Math.random() * 0.4).toFixed(2) + "ms";
        document.getElementById('latency').innerText = (1.0 + Math.random() * 0.5).toFixed(1) + "ms";
        document.getElementById('npu-load').innerText = (20 + Math.random() * 10).toFixed(0) + "%";
    }, 3000);

    function runDiag() {
        const terminal = document.getElementById('terminal');
        const row = document.createElement('div');
        row.className = 'log-row';
        row.innerHTML = `<span class="log-ts">[${new Date().toLocaleTimeString('tr-TR')}]</span> <span class="log-info">DIAG:</span> NPU health check 100%.`;
        terminal.appendChild(row);
        terminal.scrollTop = terminal.scrollHeight;
    }

    function scale() {
        const terminal = document.getElementById('terminal');
        const row = document.createElement('div');
        row.className = 'log-row';
        row.innerHTML = `<span class="log-ts">[${new Date().toLocaleTimeString('tr-TR')}]</span> <span class="log-success">SCALE:</span> Node cluster expanded.`;
        terminal.appendChild(row);
        terminal.scrollTop = terminal.scrollHeight;
    }
</script>
</body>
</html>
"""

# HTML dosyasını oluştur
FILE_NAME = "index.html"
PORT = 8000

def start_server():
    # Mevcut dizinde index.html oluştur
    with open(FILE_NAME, "w", encoding="utf-8") as f:
        f.write(html_content)

    Handler = http.server.SimpleHTTPRequestHandler

    with socketserver.TCPServer(("", PORT), Handler) as httpd:
        print(f"\\n[!] EAI Factory OS Yerel Sunucusu Başlatıldı.")
        print(f"[!] Adres: http://localhost:{PORT}")
        print(f"[!] Kapatmak için terminalde Ctrl+C tuşlarına basın.\\n")

        # Tarayıcıyı 1 saniye sonra aç
        threading.Timer(1.5, lambda: webbrowser.open(f"http://localhost:{PORT}")).start()

        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\\n[x] Sunucu kapatılıyor...")
            httpd.server_close()

if __name__ == "__main__":
    start_server()

from google.colab import userdata
userdata.get('secretName')

"""# Yeni Bölüm"""